spring.application.name=MateriaisConstrucao

# CONFIGURACAO DO BANCO DE DADOS POSTGRESQL


spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/construcaomanager}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:eduardovcn}
spring.datasource.driver-class-name=org.postgresql.Driver


# CONFIGURACOES DO JPA / HIBERNATE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# CONFIGURAÇÕES DE BACKUP E E-MAIL (GMAIL)

app.backup.cron=0 59 23 * * *
app.backup.email-destino=${MAIL_DESTINO}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==========================================
# CONFIGURACOES DO USUARIO ADMINISTRADOR
# ==========================================
app.admin.login=${ADMIN_LOGIN:admin}
app.admin.senha=${ADMIN_SENHA:admin123}

