spring.application.name=MateriaisConstrucao

# ==========================================
# CONFIGURACAO DO BANCO DE DADOS POSTGRESQL
# ==========================================
# O Postgres roda nativamente na porta 5432
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/construcaomanager}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURACOES DO JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
# Define o dialeto para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Mantem a carga inicial do data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# ==========================================
# CONFIGURAÇÕES DE BACKUP E E-MAIL (GMAIL)
# ==========================================
app.backup.cron=0 59 23 * * *
# O e-mail que VAI RECEBER o backup (o e-mail do dono/empresa)
app.backup.email-destino=${MAIL_DESTINO}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
# O e-mail que VAI ENVIAR o backup
spring.mail.username=${MAIL_USER}
# A Senha de App gerada no painel do Google
spring.mail.password=${MAIL_PASS:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

