spring.application.name=MateriaisConstrucao

# ==========================================
# CONFIGURAÇÃO DO BANCO DE DADOS MYSQL
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/construcaomanager?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=eduardovcn
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# CONFIGURAÇÕES DE CARGA INICIAL DE DADOS
# ==========================================
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always